{% set version = "1.7.0" %}
{% set sha256 = "52eba4ab6d5b60d3256c200b48e4a05fb5167296a55bf8faac17e9204b7ad075" %}

package:
  name: pepsirf
  version: {{ version }}

source:
  url: https://github.com/LadnerLab/PepSIRF/archive/refs/tags/1.7.0.zip
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('pepsirf', max_pin="x") }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
  host:
    - zlib
    - boost-cpp
  run:
    - boost-cpp

test:
  commands:
    - pepsirf demux -h
    - pepsirf enrich -h
    - pepsirf deconv -h
    - pepsirf zscore -h
    - pepsirf info -h
    - pepsirf subjoin -h

about:
  home: https://github.com/LadnerLab/PepSIRF
  license: GPL-3.0-only
  license_family: GPL3
  summary: "Peptide-based Serological Immune Response Framework."
  dev_url: https://github.com/LadnerLab/PepSIRF
