{% set name = "perl-graphviz" %}
{% set version = "2.25" %}
{% set sha256 = "1209a3ea0a40bfd3743a829396c389a30948d7925e8fb26a13317383de963ab0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETJ/GraphViz-2.25.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-xml-twig
    - perl-test-pod
    - perl-extutils-makemaker
    - perl-getopt-long
    - perl-pod-usage
    - perl-ipc-run
    - perl-file-which
    - perl-xml-xpath
    - perl-carp
    - perl-time-hires
    - perl-lib
    - perl-parse-recdescent
    - graphviz

  run:
    - perl
    - perl-xml-twig
    - perl-getopt-long
    - perl-pod-usage
    - perl-ipc-run
    - perl-time-hires
    - perl-xml-xpath
    - perl-carp
    - perl-file-which
    - perl-lib
    - perl-parse-recdescent
    - graphviz

test:
  imports:
    - GraphViz
    - GraphViz::Data::Grapher
    - GraphViz::No
    - GraphViz::Parse::RecDescent
    - GraphViz::Parse::Yacc
    - GraphViz::Parse::Yapp
    - GraphViz::Regex
    - GraphViz::Small
    - GraphViz::XML

about:
  home: http://metacpan.org/pod/GraphViz
  license: perl_5
  summary: "Interface to AT&T's GraphViz. Deprecated. See GraphViz2"

