{% set name = "mafft" %}
{% set version = "7.520" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
# url: https://mafft.cbrc.jp/alignment/software/mafft-{{ version }}-without-extensions-src.tgz
  - url: https://gitlab.com/sysimm/mafft/-/archive/v{{ version }}/mafft-v{{ version }}.zip        # [linux]
    sha256: "986042f7eb9d5aba237b7b9701974e20b6952cb7d585c66fd979137ed4a34c9b"                    # [linux]
  - url: https://mafft.cbrc.jp/alignment/software/mafft-{{ version }}-signed.pkg                  # [osx]
    sha256: "cf9751b90ecc98a8a1030750108cc53064f3da9e182e980471e93d79251e5361"                    # [osx]


build:
  number: 4
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - make                      # [linux]
    - {{ compiler('c') }}       # [linux]
    - {{ compiler('go-cgo') }}  # [linux]
  run:
    - gawk

test:
  commands:
    - mafft --version

about:
  home: 'http://mafft.cbrc.jp/alignment/software/'
  license: BSD
  summary: Multiple alignment program for amino acid or nucleotide sequences based on fast Fourier transform

extra:
  identifiers:
    - doi:10.1093/nar/gkf436
    - usegalaxy-eu:rbc_mafft
