package:
  name: perl-mailtools
  version: "2.22"

source:
  url: https://cpan.metacpan.org/authors/id/M/MA/MARKOV/MailTools-2.22.tar.gz
  sha256: 3bf68bb212298fa699a52749dddff35583a74f36a92ca89c843b854f29d87c77

build:
  number: 0
  noarch: generic
  
requirements:
  build:
    - make
  host:
    - perl
    - perl-timedate
  run:
    - perl
    - perl-timedate

test:
  # Perl 'use' tests
  imports:
    - Mail::Address
    - Mail::Cap
    - Mail::Field
    - Mail::Field::AddrList
    - Mail::Field::Date
    - Mail::Field::Generic
    - Mail::Filter
    - Mail::Header
    - Mail::Internet
    - Mail::Mailer
    - Mail::Send
    - Mail::Util

about:
  home: http://metacpan.org/pod/MailTools
  license: perl_5
  summary: 'Various e-mail related modules'
