{% set version = "0.2.4" %}

package:
  name: lib-pod5
  version: {{ version }}

source:
  git_url: https://github.com/nanoporetech/pod5-file-format/
  git_rev: {{ version }}
  sha256: f20ae5238e60c4c91f0143b3971fa688ef81e7857c5fb5ffbc65111296a38bb1

build:
  skip: true  # [py < 37]
  number: 0
  run_exports:
    - {{ pin_subpackage('lib-pod5', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - conan <2
  host:
    - python
    - setuptools_scm
    - pip
  run:
    - python
    - numpy >=1.21

test:
  imports:
    - lib_pod5

about:
  home: https://github.com/nanoporetech/pod5-file-format
  license: MPL-2.0
  license_file: LICENSE.md
  summary: 'Python bindings for the POD5 file format'
  description: |
    [![Documentation Status](https://readthedocs.org/projects/pod5-file-format/badge/?version=latest)](https://pod5-file-format.readthedocs.io/)

    **Python bindings for the POD5 file format**

    What does this project contain
    ------------------------------

    This project contains the low-level core library (extension modules) for reading and writing POD5 files.
    This project forms the basis of the pure-python [pod5 package](https://github.com/nanoporetech/pod5-file-format) which is probably the project you want.

    Documentation
    -------------

    Full documentation is found at https://pod5-file-format.readthedocs.io/
  dev_url: https://github.com/nanoporetech/pod5-file-format
  doc_url: https://pod5-file-format.readthedocs.io/

extra:
  recipe-maintainers:
    - JannesSP
  skip-lints:
    - uses_vcs_url
