{% set version = "v3.0.3" %}

package:
  name: vamb
  version: {{ version }}

source:
  url: https://github.com/RasmussenLab/vamb/archive/{{ version }}.tar.gz
  sha256: b96e075a1477b855a45e47ceac423b8ae3c56db105e5810c8bc34949462099b0

build:
  number: 0
  # Skipping py>=38 since no pytorch-cpu builds for Py3.8 are available.	  skip: True  # [py27]
  skip: True  # [py<30 or py>=38]
  entry_points:
    - vamb=vamb.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.25.2
    - setuptools >=56.0
  run:
    - python>=3.5
    - numpy >=1.15
    - pytorch-cpu >=0.4
    - pysam >=0.14
    - torchvision
    - cudatoolkit=10.2
    - pysam

test:
  imports:
    - vamb
  commands:
    - vamb --help

about:
  home: https://github.com/RasmussenLab/vamb
  license: MIT License
  license_family: MIT
  summary: Variational autoencoder for metagenomic binning

extra:
  recipe-maintainers:
    - jakobnissen
    - silask
