{% set checksum = "11e924ce74b9d1bab0d03aac74e01201d7672a32a672fe58854497296137e296" %}
{% set cmake_cxx_compiler_version = "12.4.0" %} # [linux]
{% set cmake_cxx_compiler_version = "19.1.4" %} # [osx-64]
{% set name = "openstructure" %}
{% set version = "2.9.0" %}
# To avoid having the same YAML lists in `host` and `run`, lets define a Jinja
# list and let the Jinja templating engine fill in the dependencies.
{% set dependencies = [
    "boost <1.84.0",
    "fftw >=3.3.10,<4.0a0",
    "libboost <1.84.0",
    "libboost-python <1.84.0",
    "libpng >=1.6.44,<1.7.0a0",
    "libtiff >=4.7.0,<4.8.0a0",
    "python >=3.7",
    "sqlite >=3.47.0",
    "zlib >=1.3.1",
] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  sha256: {{ checksum }}
  url: https://git.scicore.unibas.ch/schwede/{{ name|lower }}/-/archive/{{ version }}/{{ name|lower }}-{{ version }}.tar.gz

cxx_compiler_version:
  - {{ cmake_cxx_compiler_version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x.x") }}
  script_env:
    - CMAKE_CXX_COMPILER_VERSION={{ cmake_cxx_compiler_version }}
  ignore_run_exports:
    - libzlib
    - sqlite
    - zlib

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake >=3.23.1,<=3.29.0
    # Eigen is header only, after compilation not needed any more
    - eigen >=3.2
    - make >=4.4.1
  host:
  {% for dep in dependencies %}
    - {{ dep }}
  {% endfor %}
  run:
  {% for dep in dependencies %}
    - {{ dep }}
  {% endfor %}
    - networkx >=2.1
    - scipy >=1.10.1

test:
  commands:
    - lddt --help 2>&1 | grep usage
    - molck --help
    - ost --help | grep Usage
    - ost compare-ligand-structures --help
    - ost compare-structures --help
    - ost compare-structures-legacy --help
    - python -c "import sys; import ost; sys.exit(1) if ost.__version__ != '{{ version }}' else sys.exit(0)"

about:
  description: |
    This project aims to provide an open-source, modular, flexible, molecular
    modelling and visualization environment. It is targeted at interested
    method developers in the field of structural bioinformatics.
  dev_url: https://git.scicore.unibas.ch/schwede/openstructure
  doc_url: https://openstructure.org/docs/{{ version }}/
  home: https://openstructure.org/
  license: LGPL-3.0
  license_file: LICENSE.txt
  license_url: https://git.scicore.unibas.ch/schwede/openstructure/-/raw/master/LICENSE.txt
  summary: Open-Source Computational Structural Biology Framework

# ToDo: Add DOIs for the publications on the various tools
extra:
  identifiers:
    - biotools:openstructure
    - doi:10.1107/S0907444913007051
