{% set version = "1.1.2" %}

package:
  name: tabixpp
  version: {{ version }}

source:
  url: https://github.com/AndreaGuarracino/tabixpp/releases/download/v{{version}}/tabixpp-v{{version}}.tar.gz
  sha256: 61afe8638d505e73d0426817faa37d9410ad4a21aa2a058e0fcb6ad0b28122f4
  #patches:
  #  - shared_lib.patch
  #  - pkg-config.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - cmake
    - make
    - libcurl
    - zlib
    - pkg-config
  host:
    - zlib
    - bzip2
    - xz
    - htslib
    - bc
    - samtools
    - libcurl
    - pkg-config
  run:
    - zlib
    - bzip2
    - xz
    - htslib
    - bc
    - samtools
    
test:
  commands:
    - which tabix++
    

about:
  home: https://github.com/ekg/tabixpp
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: This is a C++ wrapper around tabix project which abstracts some of the details of opening and jumping in tabix-indexed files.
  maintainers: jpuritz

extra:
  recipe-maintainers:
    - AndreaGuarracino
  identifiers:
    - biotools:tabixpp
