package:
  name: perl-pegex
  version: "0.75"

source:
  url: https://cpan.metacpan.org/authors/id/I/IN/INGY/Pegex-0.75.tar.gz
  sha256: 4dc8d335de80b25247cdb3f946f0d10d9ba0b3c34b0ed7d00316fd068fd05edc

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-file-sharedir-install
    - perl-yaml-libyaml
    - perl-json-pp
    - perl-test-pod
    - perl-tie-ixhash
    - perl-xxx >=0.35
    - perl-yaml-pp >=0.019
  run:
    - perl
    - perl-extutils-makemaker
    - perl-file-sharedir-install
    - perl-yaml-libyaml
    - perl-carp 
    - perl-json-pp 
    - perl-scalar-list-utils
    - perl-xxx >=0.35
    - perl-yaml-pp >=0.019

test:
  imports:
    - Pegex

about:
  home: http://search.cpan.org/~ingy/Pegex-0.61/lib/Pegex.pod
  license: perl_5
  summary: 'Pegex Grammar for the Pegex Grammar Language'
