{% set version = "1.5.0" %}
{% set sha256 = "fe3acc37bdd5e703033b9e370f635ab9fe06ba09fd69e01fc00bc70ff6d8395a" %}

package:
  name: longreadsum
  version: {{ version }}

source:
  url: https://github.com/WGLab/LongReadSum/archive/refs/tags/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  entry_points:
    - longreadsum = entry_point:main
  run_exports:
    - {{ pin_subpackage('longreadsum', max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - swig
    - hdf5
    - htslib
    - zlib
    - setuptools
  run:
    - python
    - numpy
    - hdf5
    - htslib
    - plotly

test:
  commands:
    - longreadsum --help

about:
  home: https://github.com/WGLab/LongReadSum
  license: MIT
  summary: 'Long read sequencing data quality control tool'
  description: |
    A fast and flexible QC tool for long read sequencing data.
  dev_url: https://github.com/WGLab/LongReadSum
  doc_url: https://github.com/WGLab/LongReadSum#readme

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
