{% set version = "1.1.2" %}

package:
  name: gargammel
  version: {{ version }}

build:
  number: 2

source:
  - url: https://github.com/grenaud/gargammel/archive/{{ version }}.tar.gz
    sha256: c4b5ca081087fa5ecf086dbd49a4db0fb3c7d2d3d13eb30bdfc96b964661c3c1
  - url: https://github.com/grenaud/libgab/archive/d2bbab7d88fbfdaa0ce57a26dc908d2fc66bf656.tar.gz
    sha256: ef4d4e980918f48b9a5c454f46afe3ffe6d97a075bbbf89abb7e3553cd6b9827
    folder: libgab
    patches:
      - 0001-libgab-gzstream-use-CXXFLAGS-and-LDFLAGS.patch

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - gsl
    - samtools
    - bamtools
  run:
    - zlib
    - perl
    - gsl
    - art
    - samtools

about:
  home: https://github.com/grenaud/gargammel
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Tool for simulating ancient DNA datasets

test:
  commands:
    - gargammel --help    
    - adptSim --help | grep -q 'adptSim'
    - deamSim --help | grep -q 'deamSim'
    - fasta2fastas --help | grep -q 'fasta2fastas'
    - fragSim --help | grep -q 'fragSim'
