{% set name = "HapCUT2" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/vibansal/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: f241215f9f601868919effc16a578be1c4c479bbc1fb859c468fe821cb93a6e3
    patches:
    - flags.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
  host:
    - zlib
    - htslib
  run:
    - zlib
    - python >=3.5
    - pysam
    - htslib

test:
  commands:
    - "hapcut2 | grep HapCUT2"
    - "HAPCUT2 | grep HapCUT2"
    - 'calculate_haplotype_statistics.py 2>&1 | grep "Calculate statistics"'
    - 'LinkFragments.py 2>&1 | grep "usage: LinkFragments.py"'

about:
  summary: Tools for haplotype assembly from sequence data
  home: https://github.com/vibansal/HapCUT2/
  license: BSD-2-Clause
  license_file: LICENSE
