{% set name = "perl-datetime-format-strptime" %}
{% set version = "1.79" %}
{% set sha256 = "701e46802c86ed4d88695c1a6dacbbe90b3390beeb794f387e7c792300037579" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Format-Strptime-1.79.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-test-fatal
    - perl-lib
    - perl-exporter
    - perl-params-validationcompiler
    - perl-datetime-timezone
    - perl-parent
    - perl-specio
    - perl-test-warnings
    - perl-package-deprecationmanager
    - perl-carp
    - perl-datetime
    - perl-constant
    - perl-extutils-makemaker
    - perl-try-tiny
    - perl-datetime-locale >=1.05
    - perl-findbin
  run:
    - perl
    - perl-exporter
    - perl-params-validationcompiler
    - perl-parent
    - perl-specio
    - perl-package-deprecationmanager
    - perl-carp
    - perl-datetime
    - perl-constant
    - perl-try-tiny
    - perl-datetime-timezone
    - perl-datetime-locale >=1.30

test:
  imports:
    - DateTime::Format::Strptime
    - DateTime::Format::Strptime::Types

about:
  home: http://metacpan.org/release/DateTime-Format-Strptime
  license: artistic_2
  summary: 'Parse and format strp and strf time patterns'

