{% set name = "perl-file-sharedir-install" %}
{% set version = "0.14" %}
{% set sha256 = "8f9533b198f2d4a9a5288cbc7d224f7679ad05a7a8573745599789428bc5aea0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/File-ShareDir-Install-0.14.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-exporter
    - perl-extutils-makemaker
    - perl-carp
    - perl-file-path

  run:
    - perl
    - perl-exporter
    - perl-carp

test:
  imports:
    - File::ShareDir::Install

about:
  home: https://github.com/Perl-Toolchain-Gang/File-ShareDir-Install
  license: perl_5
  summary: 'Install shared files'
