{% set name = "perl-perlio-utf8_strict" %}
{% set version = "0.010" %}
{% set sha256 = "bcd2848b72df290b5e984fae8b1a6ca96f6d072003cf222389a8c9e8e1c570cd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/L/LE/LEONT/PerlIO-utf8_strict-0.010.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}

  host:
    - perl
    - perl-carp
    - perl-test-exception
    - perl-lib
    - perl-exporter
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - PerlIO::utf8_strict

about:
  home: http://metacpan.org/pod/PerlIO::utf8_strict
  license: perl_5
  summary: 'Fast and correct UTF-8 IO'
