{% set name = "comet-ms" %}
{% set version = "2022.01.2" %}
{% set sha256 = "1774e3a2770c6d37b1889336ba4cc1688e702d4bae01ff9751a5791064453188" %}

package:
  name: {{ name }}
  version: {{ version | replace(".", "") }}

source:
  url: https://github.com/UWPR/Comet/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # skip: True  # [osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  # host:
  #   - expat
  # run:
  #   - expat
test:
  commands:
    - comet.exe -p && rm comet.params.new
    - comet -p && rm comet.params.new

about:
  home: https://uwpr.github.io/Comet/
  license: Apache License 2.0
  summary: 'Comet is a command line tool that does MS/MS database search.'

extra:
  identifiers:
    - doi:10.1007/s13361-015-1179-x
    - doi:10.1002/pmic.201200439
