package:
  name: wheezy.template
  version: "3.1.0"

source:
  url: https://files.pythonhosted.org/packages/9f/81/659038f48d53bb1a9f4ff97b8b2c53f2cb7ff60003b22d57b4dd22d8da0c/wheezy.template-3.1.0.tar.gz
  sha256: e11007cac73368dce12998e34b66c476016bb461471ffc1e4d56e84002ec960f

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wheezy
    - wheezy.template
    - wheezy.template.ext

about:
  home: https://bitbucket.org/akorn/wheezy.template
  license: MIT
  summary: 'A lightweight template library'
  license_family: MIT
