{% set name = "medaka" %}
{% set version = "0.12.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee1b39980090285a87ff6b2e3b46e6ab0a495cfb81f8c46d7eb2106862c2ee1a

build:
  number: 1
  skip: True # [not py36]
  entry_points:
    - medaka = medaka.medaka:main
    - medaka_counts = medaka.medaka_counts:main
    - medaka_data_path = medaka.common:print_data_path
    - medaka_version_report = medaka:report_binaries

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cffi
    - pip
    - python
    - htslib
    - bzip2
    - xz
    - zlib
  run:
    - biopython
    - cffi
    - h5py
    - intervaltree >=3.0.0
    - mappy
    - numpy
    - ont-fast5-api
    - parasail-python
    - pysam >=0.15.2
    - python
    - tensorflow 1.*
    - whatshap
    - samtools
    - bcftools
    - minimap2
    - htslib

test:
  imports:
    - medaka
  commands:
    - medaka --help
    - medaka consensus --help
    - medaka_data_path
    - medaka_version_report

about:
  home: https://github.com/nanoporetech/medaka
  license: Mozilla Public License 2.0
  license_family: OTHER
  license_file: LICENSE.md
  summary: Neural network sequence error correction.
  doc_url: https://nanoporetech.github.io/medaka/index.html
  dev_url: https://github.com/nanoporetech/medaka

extra:
  recipe-maintainers:
    - cjw85
