package:
  name: perl-ipc-run
  version: "20220807.0"

source:
  url: https://cpan.metacpan.org/authors/id/T/TO/TODDR/IPC-Run-20220807.0.tar.gz
  sha256: 277d781dbbc98af18e979c7ef36f222513d7361742c52507c3348b265f6f5e69

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-io-tty

  run:
    - perl
    - perl-io-tty

test:
  # Perl 'use' tests
  imports:
    - IPC::Run
    #- IPC::Run::IO            # [not win]
    #- IPC::Run::Timer
    #- IPC::Run::Win32Helper   # [win]
    #- IPC::Run::Win32IO       # [win]
    #- IPC::Run::Win32Pump     # [win]

about:
  home: http://metacpan.org/pod/IPC-Run
  license: perl_5
  summary: 'system() and background procs w/ piping, redirs, ptys (Unix, Win32)'
