{% set version = "0.3.0" %}

package:
  name: stemcnv-check
  version: {{ version }}

source:
  url: https://github.com/bihealth/StemCNV-check/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 14096ea48ee487a0450f9e548876098bd30d87defebcdf6ba6aa564fd56f42f0

build:
  number: 0
  noarch: python
  entry_points:
    - stemcnv-check=stemcnv_check.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  run_exports:
    - {{ pin_subpackage('stemcnv-check', max_pin="x") }}
  always_include_files:
    - app
    - control_files
    - envs
    - rules
    - scripts
    - supplemental-files  

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=3.12
    - snakemake-minimal >=8,<9
    - ruamel.yaml >=0.18
    - loguru >=0.7
    - pandas >=2.2
    - openpyxl >=3.1
    - xlsxwriter >=3.2
    - pydantic >=2.8
    - deepdiff >=8.0
    - apptainer

test:
  imports:
    - stemcnv_check
  commands:
    - stemcnv-check --help
    - stemcnv-check setup-files

about:
  home: https://github.com/bihealth/StemCNV-check
  license: MIT License
  summary: 'StemCNV-check: CNV Based Quality Control Workflow for Stem Cell SNP Array Data'
  license_family: MIT
  license_file: LICENSE
  # doc_url: https://pythonhosted.org/pyfaidx/

# extra:
#   identifiers:
#      - doi:...