{% set name = "M-PARTY" %}
{% set version = "0.3.0" %}
{% set sha256 = "bc9cf9055e0121a6bf882419987df0e27c41c0bbddff15961d537544c8fa52fc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ozefreitas/M-PARTY/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage('m-party', max_pin="x.x") }}

requirements:
  run:
    - upimapi
    - pyyaml
    - hmmer
    - t-coffee
    - cd-hit
    - pandas
    - openpyxl
    - snakemake-minimal
    - clint

test:
  commands:
    - m-party -h
    # - m-party -i $INSTALL_FOLDER/lit_sequences.fasta -o output_results -rt --output_type excel

about:
  home: https://github.com/ozefreitas/M-PARTY
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Mining Protein dAtasets foR Targeted EnzYmes.'
  description: |
    M-PARTY takes an input FASTA file with a variable number of aminoacidic
    sequences and performes a search against an considerable amount of Hidden 
    Markov Models, previously built and trained from state of the art plastic 
    (PE - polyethylene) degrading enzymes. This process relies on the hmmsearch 
    function from HMMER to perform the structural annotation. Output deduces 
    about the potential presence of plastic degradring enzymes in the inputed
    sequences, and is composed by 3 distinct files, in order to help the user 
    to have an easier time to read and conclude about the results.
  doc_url: https://github.com/ozefreitas/M-PARTY/blob/main/README.md
  dev_url: https://github.com/ozefreitas/M-PARTY 

extra:
  recipe-maintainers:
    - ozefreitas
